# CS375 Final Project / Presentation
# Shafkat Haque & Rachael Wang

all: dijkstras

dijkstras: dijkstras.o
	gcc dijkstras.o -o dijkstras

dijkstras.o: dijkstras.cpp
	gcc -c dijkstras.cpp

clean: 
	rm -f *.o dijkstras *~